openapi: 3.0.0
info:
  title: KielCloak
  description: API fuer die Kommunikation zwischen Front- und Backend von mein.Kiel App
  version: "1.0.0"
paths:
  /send_address:
    post:
      summary: Neue Adresse inkl. TTL-Datei senden
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                address_src_url:
                  type: string
                  format: uri
                  description: URL zu "adress.ttl" im Studenten Pod
                target_src_urls:
                  type: array
                  items:
                    type: string
                  example:
                    [
                      "https://solid.valetudo.casa/uni/MailBox",
                      "https://solid.valetudo.casa/bank/MailBox",
                    ]
                web_id:
                  type: string
                  description: "WebId zum Solid Pod des Nutzers"
                  example: "https://solid.valetudo.casa/stud/profile/card#me"
              required:
                - address_src_url
                - target_src_urls
                - web_id
      responses:
        "200":
          description: Address saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        "400":
          description: Invalid input
  /antrag/new:
    post:
      summary: Antrag inkl. TTL-Datei senden
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                web_id:
                  type: string
                  description: "WebId zum Solid Pod des Nutzers"
                  example: "https://solid.valetudo.casa/stud/profile/card#me"
                antrag_type:
                  type: string
                  description: Art des Antrags
                  example: "begruessungsgeld"
                ttl_file:
                  type: string
                  format: binary
                  description: antrags-TTL Datei
              required:
                - antrag_type
                - ttl_file
      responses:
        "200":
          description: Antrag gespeichert
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        "400":
          description: Invalid input or duplicate application
        "500":
          description: Server error
        "401":
          description: Unauthorized
  /antrag/all:
    get:
      summary: Gibt alle Anträge des Nutzers zurück
      parameters:
        - name: web_id
          in: query
          required: true
          description: WebId zum Solid Pod des Nutzers
          schema:
            type: string
            example: https://solid.valetudo.casa/stud/profile/card#me
      responses:
        "200":
          description: JSON mit Anträgen des Nutzers (timestamp und antrag-type)
          content:
            application/json:
              schema:
                type: object
                properties:
                  forms:
                    type: array
                    items:
                      type: object
                      properties:
                        antragType:
                          type: string
                          example: begruessungsgeld
                        timestamp:
                          type: integer
                          format: int64
                          example: 1768143644
                  status:
                    type: string
                    example: ok
        "400":
          description: "Nutzer nicht gefunden"
  /send_webid:
    post:
      summary: Meldung der WebId des Studenten
      description: Meldung der WebId des Studenten Pods an KielCloak und damit dann an den Vermieter-Pod (KielCloak leitet die WebId weiter)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tenantWebId:
                  type: string
                  description: "WebId zum Solid Pod des Studenten"
                  example: "https://solid.valetudo.casa/stud/profile/card#me"
                givenName:
                  type: string
                  description: "Vorname des Studenten"
                  example: "Petra"
                familyName:
                  type: string
                  description: "Nachname des Studenten"
                  example: "Plietsch"
                fullName:
                  type: string
                  description: "Voller Name des Studenten"
                  example: "Petra Clara Plietsch"
                landlordWebId:
                  type: string
                  description: "WebId des Vermieter Pods"
                  example: "https://solid.valetudo.casa/lord/profile/card#me"
              required:
                - tenantWebId
                - givenName
                - familyName
                - fullName
                - landlordWebId
      responses:
        "200":
          description: Address saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        "400":
          description: Invalid input
