@startuml Adresse an Dritten nach Ummeldungsprozess weiterleiten

participant UserPod
actor User
participant Frontend
participant KielCloak
actor "Solid Pod des Backend" as KielPod

== Antrag im Solid Pod des Backends nach Ummeldungsprozess für den User speichern ==

Frontend -> UserPod : Liest Profildaten aus Pod
UserPod --> Frontend
Frontend -> UserPod : Liest Adresse aus addressbesteatigung-{Milisekunden}.ttl
Frontend -> User : Fragt, ob Daten richtig sind\n(über Zusammenfassungsseite)
User -> Frontend : Bestätigung
Frontend -> KielCloak : /antrag/new(WebID, Antrags-Typ \n und Antrags-TTL als Blob
KielCloak -> KielCloak : Konvertiert WebID in Base64 um
alt Antrags-Typ ist "begruessungsgeld"
    KielCloak -> KielPod: Fragt alle Dateien im Container ./antraege/ an
    KielPod --> KielCloak: Response mit Dateiliste
    KielCloak -> KielCloak: Prüft, ob bereits eine Datei mit dieser WebID mit Antrags-Typ existiert
        KielCloak --> Frontend : Response Error: Begruessungsgeld bereits beantragt
        Frontend -> User : Fehlermeldung
    else Antrags-Typ ist nicht begruessungsgeld oder noch nicht beantragt
    KielCloak -> KielCloak: Erstellt aktuellen Timestamp in Millisekunden
    KielCloak -> KielCloak : Erstellt Dateiname aus Antrags-Typ und WebID und Timestamp
    alt Antrag existiert bereits für User
        KielCloak --> Frontend : Response Error: Antrag existiert bereits
        Frontend -> User : Fehlermeldung
    else Antrag existiert nicht für User
      KielCloak -> KielCloak : Erstellt ACL für Antrags-TTL (User bekommt nur Leserechte)
        KielCloak -> KielPod : Speichert Antrags-TTL mit Dateinamen im Container ./antraege/
        KielPod --> KielCloak : Response OK
        KielCloak -> KielPod : Speichert ACL zur Antrags-TTL im Container ./antraege/
        KielPod --> KielCloak : Response OK
        KielCloak --> Frontend : Response OK
        Frontend -> User : Erfolgsmeldung
    end
end
@enduml
